export const students = [
  {
    id: 0,
    email: 'khushilshah2105@gmail.com',
    name: 'KHUSHIL HITESH SHAH',
    type: '1st',
    isActive: true,
  },
  {
    id: 1,
    email: 'nishitmistry94@gmail.com',
    name: 'Mistry nishit premkumar',
    type: '1st',
    isActive: true,
  },
  {
    id: 2,
    email: 'tirthsavalia@gmail.com',
    name: 'Tirth Savalia ',
    type: '1st',
    isActive: true,
  },
  {
    id: 3,
    email: 'meetbpatel2406@gmail.com',
    name: 'Meet b patel',
    type: 'participant',
    isActive: true,
  },
  {
    id: 4,
    email: 'gauravgjani@gmail.com',
    name: 'Gaurav Jani ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 5,
    email: 'krishsutharofficial@gmail.com',
    name: 'Krish Suthar',
    type: 'participant',
    isActive: true,
  },
  {
    id: 6,
    email: 'mitpanchal1512@gmail.com',
    name: 'Mit Sureshbhai Panchal',
    type: '2nd',
    isActive: true,
  },
  {
    id: 7,
    email: 'kapadiakutbuddin@gmail.com',
    name: 'Kutbuddin kapadia',
    type: 'participant',
    isActive: true,
  },
  {
    id: 8,
    email: 'sanskrutidhanani78@gmail.com',
    name: 'Sanskruti Dhanani',
    type: 'participant',
    isActive: true,
  },
  {
    id: 9,
    email: 'sanganiharsh786@gmail.com',
    name: 'Sangani Harsh Jaysukhbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 10,
    email: 'dhruvpatel2636@gmail.com',
    name: 'BALDHA DHRUV ALKESHBHAI',
    type: 'participant',
    isActive: true,
  },
  {
    id: 11,
    email: '2021002170110039@ljku.edu.in',
    name: 'Dhaval AshokBhai Gondaliya ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 12,
    email: '2021002170210056@ljku.edu.in',
    name: 'PARMAR MANSI RAJESHBHAI',
    type: 'participant',
    isActive: true,
  },
  {
    id: 13,
    email: 'safi.shaikh360@gmail.com',
    name: 'Safi Shaikh',
    type: 'participant',
    isActive: true,
  },
  {
    id: 14,
    email: 'gja5364@gmail.com',
    name: 'Goti Jemish Arvindbhai ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 15,
    email: 'joyalshah07@gmail.com',
    name: 'Joyal Rakeshkumar Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 16,
    email: 'asrrajput123ajit@gmail.com',
    name: 'RAJPUT AJITSINH SURENDRASINH ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 17,
    email: 'sonikartavya8@gmail.com',
    name: 'KARTAVYA SONI',
    type: 'participant',
    isActive: true,
  },
  {
    id: 18,
    email: 'utp4441@gmail.com',
    name: 'Pandey Utkarsh PanditGovind',
    type: 'participant',
    isActive: true,
  },
  {
    id: 19,
    email: 'pparthiv077@gmail.com',
    name: 'Parthiv Patel',
    type: 'participant',
    isActive: true,
  },
  {
    id: 20,
    email: 'divyeshgurjar2004@gmail.com',
    name: 'gurjar  divyesh vimalkumar',
    type: 'participant',
    isActive: true,
  },
  {
    id: 21,
    email: 'hetpatel151103@gmail.com',
    name: 'Het Ghanshyambhai Patel',
    type: 'participant',
    isActive: true,
  },
  {
    id: 22,
    email: 'asthamakwana2003@gmail.com',
    name: 'Makwana Astha Jatinbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 23,
    email: 'keyushkarm@gmail.com',
    name: 'Prajapati Keyush Janakbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 24,
    email: 'jinaydoshi2003@gmail.com',
    name: 'Jinay Doshi',
    type: 'participant',
    isActive: true,
  },
  {
    id: 25,
    email: 'bhavyaaes@gmail.com',
    name: 'Bhavya C Patel ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 26,
    email: 'diyanshu3529@gmail.com',
    name: 'Diyanshu Anilkumar Patel ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 27,
    email: 'karan.patel.kpau@gmail.com',
    name: 'Karan Umangkumar Patel',
    type: 'participant',
    isActive: true,
  },
  {
    id: 28,
    email: '2021002170110208@ljku.edu.in',
    name: 'Virti Pratikkumar Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 29,
    email: 'henilsuhagiya0@gmail.com',
    name: 'Henil Suhagiya',
    type: 'participant',
    isActive: true,
  },
  {
    id: 30,
    email: '190320107097.ce.zeenat.puthawala@gmail.com',
    name: 'Zeenat Puthawala',
    type: 'participant',
    isActive: true,
  },
  {
    id: 31,
    email: '190320107131.ce.zeel.soni@gmail.com',
    name: 'Zeel Soni',
    type: 'participant',
    isActive: true,
  },
  {
    id: 32,
    email: 'harrygajjar2004@gmail.com',
    name: 'Gajjar Harikrishna Rajeshbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 33,
    email: 'jaykalariya1208@gmail.com',
    name: 'Kalariya Jay Vinodkumar',
    type: 'participant',
    isActive: true,
  },
  {
    id: 34,
    email: '190320107042.ce.harshil.mehta@gmail.com',
    name: 'Harshil Hitesh Mehta',
    type: 'participant',
    isActive: true,
  },
  {
    id: 35,
    email: 'kalashshah9009@gmail.com',
    name: 'Kalash Ketanbahi Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 36,
    email: '2021002170110064@ljku.edu.in',
    name: 'AAFAK AARIZ LIGHTWALA',
    type: 'participant',
    isActive: true,
  },
  {
    id: 37,
    email: 'anshumaheshwari025@gmail.com',
    name: 'Anshu Rajeshkumar Maheshwari',
    type: 'participant',
    isActive: true,
  },
  {
    id: 38,
    email: 'guptavanshil25@gmail.com',
    name: 'Vanshil Gupta',
    type: 'participant',
    isActive: true,
  },
  {
    id: 39,
    email: '190320111031.ec.bhavanshu.nyati@gmail.com',
    name: 'Bhavanshu Nyati',
    type: 'participant',
    isActive: true,
  },
  {
    id: 40,
    email: 'riyazahemad7486@gmail.com',
    name: 'Riyazahmed N Momin',
    type: 'participant',
    isActive: true,
  },
  {
    id: 41,
    email: 'shreyshah206@gmail.com',
    name: 'Shrey Samirkumar Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 42,
    email: 'shahnaman004@gmail.com',
    name: 'Naman H Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 43,
    email: '190320107039.ce.anjali.mandowara@gmail.com',
    name: 'Anjali Mandowara',
    type: 'participant',
    isActive: true,
  },
  {
    id: 44,
    email: 'hevinpatel6351@gmail.com',
    name: 'Patel Hevinkumar Harishbhai ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 45,
    email: 'shahadit68@gmail.com',
    name: 'Adit shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 46,
    email: 'harshdobariya79@gmail.com',
    name: 'Harsh Dobariya',
    type: 'participant',
    isActive: true,
  },
  {
    id: 47,
    email: 'vishwaraval247@gmail.com',
    name: 'Vishwa Raval',
    type: 'participant',
    isActive: true,
  },
  {
    id: 48,
    email: 'hinsubadal@gmail.com',
    name: 'Badal hinsu',
    type: 'participant',
    isActive: true,
  },
  {
    id: 49,
    email: 'seanpatel180703@gmail.com',
    name: 'Sean Patel ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 50,
    email: 'mirekal2404@gmail.com',
    name: 'Miral Vijay Katpara',
    type: 'participant',
    isActive: true,
  },
  {
    id: 51,
    email: 'meet.vakhariam@gmail.com',
    name: 'MEET MAYANKBHAI VAKHARIA',
    type: 'participant',
    isActive: true,
  },
  {
    id: 52,
    email: 'shagunpatel9903@gmail.com',
    name: 'Shagun patel',
    type: 'participant',
    isActive: true,
  },
  {
    id: 53,
    email: 'aagam1288@gmail.com',
    name: 'Aagam ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 54,
    email: 'indrajeetsingh083@gmail.com',
    name: 'Indrajeet Singh',
    type: 'participant',
    isActive: true,
  },
  {
    id: 55,
    email: 'mansiramoliya58@gmail.com',
    name: 'RAMOLIYA MANSI JAYESHBHAI ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 56,
    email: 'lakum2002kunal@gmail.com',
    name: 'Lakum Kunal ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 57,
    email: 'manav762003@gmail.com',
    name: 'Manav Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 58,
    email: 'poojapatel1312004@gmail.com',
    name: 'Patel Pooja Maheshkumar',
    type: 'participant',
    isActive: true,
  },
  {
    id: 59,
    email: 'laramak2509@gmail.com',
    name: 'Lara Makwana P.',
    type: 'participant',
    isActive: true,
  },
  {
    id: 60,
    email: 'khushildiyora@gmail.com',
    name: 'Khushil diyora',
    type: 'participant',
    isActive: true,
  },
  {
    id: 61,
    email: '2021002171210129@ljku.edu.in',
    name: 'Patel Vidhi Mukeshkumar ',
    type: '3rd',
    isActive: true,
  },
  {
    id: 62,
    email: 'krishpitroda08@gmail.com',
    name: 'Pitroda krish kalpeshbhai ',
    type: '3rd',
    isActive: true,
  },
  {
    id: 63,
    email: 'dspatelb107@gmail.com',
    name: 'Dhruvin Patel ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 64,
    email: 'connect.hetvi@gmail.com',
    name: 'Hetvi Patel',
    type: 'participant',
    isActive: true,
  },
  {
    id: 65,
    email: 'pavitrausdadiya112@gmail.com',
    name: 'Pavitraben Prafulbhai Usdadiya',
    type: 'participant',
    isActive: true,
  },
  {
    id: 66,
    email: 'vhs180903@gmail.com',
    name: 'Vruddhi Hemant Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 67,
    email: 'sahildodiyasahildodiya1@gmail.com',
    name: 'Dodiya Sejalben Haribhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 68,
    email: 'infohetanshishah@gmail.com',
    name: 'Hetanshi Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 69,
    email: '2021002170210015@ljku.edu.in',
    name: 'Radhika Desai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 70,
    email: 'malakbhagat@gmail.com',
    name: 'BHAGAT MALAK CHIRAG BHAI',
    type: 'participant',
    isActive: true,
  },
  {
    id: 71,
    email: 'sameepkhatri2516@gmail.com',
    name: 'Khatri Sameep Pareshbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 72,
    email: 'hemangivarkal1612@gmail.com',
    name: 'Hemangi Chandraprakash Varkal',
    type: 'participant',
    isActive: true,
  },
  {
    id: 73,
    email: 'zealoza45@gmail.com',
    name: 'Zeal Chiragbhai oza',
    type: 'participant',
    isActive: true,
  },
  {
    id: 74,
    email: '2021002170510014@ljku.edu.in',
    name: 'Dimple Makwana ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 75,
    email: 'tanisha552004@gmail.com',
    name: 'Tanisha Jayeshkumar Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 76,
    email: '2021002170410014@ljku.edu.in',
    name: 'Sehba Hawawala Ushama',
    type: 'participant',
    isActive: true,
  },
  {
    id: 77,
    email: 'harsh.hapaliya25@gmail.com',
    name: 'Harsh Hapaliya',
    type: 'participant',
    isActive: true,
  },
  {
    id: 78,
    email: 'pateldhairya0210@gmail.com',
    name: 'PATEL DHAIRYA LALITKUMAR',
    type: 'participant',
    isActive: true,
  },
  {
    id: 79,
    email: 'abhishekmakwana7021@gmail.com',
    name: 'Makwana Abhishek Rameshbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 80,
    email: 'nairajdoctor@gmail.com',
    name: 'Naira Doctor',
    type: 'participant',
    isActive: true,
  },
  {
    id: 81,
    email: 'shahaayush459@gmail.com',
    name: 'Aayush  Shah ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 82,
    email: 'bhavikabhavi188@gmail.com',
    name: 'Bhavika Gehani ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 83,
    email: 'kevinpatel2383@gmail.com',
    name: 'Kevin Patel',
    type: 'participant',
    isActive: true,
  },
  {
    id: 84,
    email: 'aaliyar2003@gmail.com',
    name: 'Rangoonwala Aaliya Asfak ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 85,
    email: 'thakkar_b21@rediffmail.com',
    name: 'Aayushi thakkar',
    type: 'participant',
    isActive: true,
  },
  {
    id: 86,
    email: 'vchokshi6403@gmail.com',
    name: 'Vishwa Chokshi',
    type: 'participant',
    isActive: true,
  },
  {
    id: 87,
    email: 'shahdevanshi2907@gmail.com',
    name: 'Devanshi Shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 88,
    email: 'varshilbhojak@gmail.com',
    name: 'Bhojak Varshilkumar Hiteshbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 89,
    email: 'patidarlion584@gmail.com',
    name: 'Patel Prem',
    type: 'participant',
    isActive: true,
  },
  {
    id: 90,
    email: 'modiperin@gmail.com',
    name: 'Perin Modi',
    type: 'participant',
    isActive: true,
  },
  {
    id: 91,
    email: 'harvigajera@gmail.com',
    name: 'Gajera Harvi Varishbhai ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 92,
    email: 'amitvatyani2001@gmail.com',
    name: 'Amit Vatyani',
    type: 'participant',
    isActive: true,
  },
  {
    id: 93,
    email: 'zalalovekush@gmail.com',
    name: 'Zala Kushrajsinh Tripalsinh',
    type: 'participant',
    isActive: true,
  },
  {
    id: 94,
    email: 'palakvekariya2111@gmail.com',
    name: 'Palak vekariya',
    type: 'participant',
    isActive: true,
  },
  {
    id: 95,
    email: 'parthpatel06072004@gmail.com',
    name: 'PATEL PARTH HITESH ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 96,
    email: 'jngengg04@gmail.com',
    name: 'Jeet N Gaikwad',
    type: 'participant',
    isActive: true,
  },
  {
    id: 97,
    email: 'krishthakker55@gmail.com',
    name: 'Thakkar krish Rajeshbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 98,
    email: 'kushalyadav440@gmail.com',
    name: 'Kushal yadav',
    type: 'participant',
    isActive: true,
  },
  {
    id: 99,
    email: '190320107072.ce.meshwa.patel@gmail.com',
    name: 'Patel Meshwa Nimeshkumar ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 100,
    email: 'luckyprajapati28022004@gmail.com',
    name: 'PRAJAPATI LUCKY HASMUKHBHAI',
    type: 'participant',
    isActive: true,
  },
  {
    id: 101,
    email: 'jainipurohit735@gmail.com',
    name: 'Jaini Purohit',
    type: 'participant',
    isActive: true,
  },
  {
    id: 102,
    email: '2021002170110155@ljku.edu.in',
    name: 'RATHOD KULDIPKUMAR JAGDISHBHAI',
    type: 'participant',
    isActive: true,
  },
  {
    id: 103,
    email: 'jneel3866@gmail.com',
    name: 'Neelkanth Joshi',
    type: 'participant',
    isActive: true,
  },
  {
    id: 104,
    email: 'nidhidjm28@gmail.com',
    name: 'Mulani Nidhi Deepeshbhai',
    type: 'participant',
    isActive: true,
  },
  {
    id: 105,
    email: 'ashvipalkhiwala2401@gmail.com',
    name: 'Yashvi Palkhiwala ',
    type: 'participant',
    isActive: true,
  },
  {
    id: 106,
    email: 'vrajshah3025@gmail.com',
    name: 'vraj shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 107,
    email: 'shahsiddh08@gmail.com',
    name: 'siddh divyesh shah',
    type: 'participant',
    isActive: true,
  },
  {
    id: 108,
    email: 'smitkanzariya2003@gmail.com',
    name: 'KANZARIYA SMIT BHARATBHAI',
    type: 'participant',
    isActive: true,
  },
  /* MENTORS */
  {
    id: 109,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Devanshu Shah',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 110,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Kriyanshi Shah',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 111,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Fagun Doshi',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 112,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Eshika Jagani',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 113,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Dhrumin Mittal',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 114,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Yagna Patel',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 115,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Ishan Pathak',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 116,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Aarjav Panchal',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 117,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Kaiwal Panchal',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 118,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Vivek Thobhani',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 119,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Shivam Tripathi',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 120,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Yash Patel',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 121,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Yashvi Joshipura',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 122,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Urvesh Patel ',
    type: 'mentor',
    isActive: true,
  },
  {
    id: 123,
    email: 'smitkanzariya2003@gmail.com',
    name: 'Samyak Shah',
    type: 'mentor',
    isActive: true,
  },

]
